# reference: https://github.com/marketplace/actions/build-and-push-docker-images#git-context
# reference: https://docs.docker.com/ci-cd/github-actions/
name: on push ci

on:
  repository_dispatch:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/386,linux/amd64,linux/arm/v7,linux/arm64/v8
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
